# More with NumPy

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[11,12,13],[14,15,16]])

* Stacking

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2

array([[11, 12, 13],
       [14, 15, 16]])

In [ ]:
# hstack() & vstack()

In [ ]:
np.vstack([arr1,arr2,arr1,arr1])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [ ]:
np.hstack([arr1,arr2])

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [ ]:
arr3 = np.array([100,200,300])

In [ ]:
np.vstack((arr1,arr3))

array([[  1,   2,   3],
       [  4,   5,   6],
       [100, 200, 300]])

In [ ]:
np.hstack((arr1,arr3))

ValueError: ignored

In [ ]:
arr3

array([100, 200, 300])

In [ ]:
arr4 = np.array([500,600,700])

In [ ]:
arr4

array([500, 600, 700])

In [ ]:
# dstack
np.dstack((arr3,arr4))

array([[[100, 500],
        [200, 600],
        [300, 700]]])

* Spliting

In [ ]:
arr3

array([100, 200, 300])

In [ ]:
# array_split()

br = np.array_split(arr3,10)

In [ ]:
br

[array([100]),
 array([200]),
 array([300]),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64)]

* Searching

In [ ]:
newarr = np.array([1,2,3,4,5,4,4])

In [ ]:
newarr

array([1, 2, 3, 4, 5, 4, 4])

In [ ]:
# where

np.where(newarr<4)

(array([0, 1, 2]),)

* Sorting

In [ ]:
newarr = np.array([10,5,6,-10,-7,20,0,4,4.5,18])

In [ ]:
newarr

array([ 10. ,   5. ,   6. , -10. ,  -7. ,  20. ,   0. ,   4. ,   4.5,
        18. ])

In [ ]:
# Ascending

np.sort(newarr)

array([-10. ,  -7. ,   0. ,   4. ,   4.5,   5. ,   6. ,  10. ,  18. ,
        20. ])

In [ ]:
# Descending

-np.sort(-newarr)

array([ 20. ,  18. ,  10. ,   6. ,   5. ,   4.5,   4. ,   0. ,  -7. ,
       -10. ])

* Any() & All()

In [ ]:
newarr = np.array([2,4,6,8,10])

In [ ]:
newarr

array([2, 4, 6, 8, 9])

In [ ]:
# Any
np.any(newarr%2==0)

True

In [ ]:
# All
np.all(newarr%2==0)

True

* resize()

In [ ]:
a = np.arange(12)

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.reshape(a,(3,5))

ValueError: ignored

In [ ]:
np.resize(a,(3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2]])

In [ ]:
np.resize(a,(10,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8,  9, 10, 11,  0,  1],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  0,  1,  2,  3]])

* Delete

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# delete(arr, obj, axis)

np.delete(a,5)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [ ]:
delmat = np.array([[1,2,3],[4,3,5]])

In [ ]:
delmat

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
np.delete(delmat,1,axis=1)

# Ouput [1,2][4,5], Shape - 2x2, Dim - 1


array([[1, 3],
       [4, 5]])

* LCM

In [ ]:
# lcm(num1,num2)
num1 = 25
num2 = 125
num3 = 625

np.lcm()

TypeError: ignored

In [ ]:
np.lcm.reduce((num2,num3, num1))

ValueError: ignored

In [ ]:
newarr

array([ 2,  4,  6,  8, 10])

In [ ]:
np.lcm.reduce(newarr)

# 10
# Error
# 120

120

In [ ]:
np.lcm.reduce((num2,num3, num1))

625

* GCD

In [ ]:
a = 16
b = 32

# gcd()

np.gcd(a,b)

16

In [ ]:
np.gcd.reduce(newarr)

2

In [ ]:
newarr

array([ 2,  4,  6,  8, 10])

* Linear Equation

In [ ]:
3x + y = 9
x + 2y = 8

In [ ]:
a = np.array([[3,1],[1,2]])
b = np.array([9,8])

In [ ]:
a

array([[3, 1],
       [1, 2]])

In [ ]:
b

array([9, 8])

In [ ]:
# np.linalg.solve(a,b)
np.linalg.solve(a,b)

array([2., 3.])

* Quadractic Equation

In [ ]:
x^2 + 4x = -4
x^2 + 4x + 4 = 0

In [ ]:
coeff = np.array([1,4,4])

In [ ]:
# roots()
np.roots(coeff)

array([-2., -2.])

* vdot()

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,20,30],[40,50,60]])

1*10 + 2*20 + .......... + 6*60

In [ ]:
np.vdot(a,b)

910

* Mean

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.mean(a)

3.5

* Weighted Mean

In [ ]:
array = np.array([1,2,3,4])
weight = np.array([4,3,2,1])

(1*4 + 2*3 + 3*2 + 4*1)/(4+3+2+1)

In [ ]:
# average(array, weight=weight)

np.average(array,weights=weight)

2.0

In [ ]:
NumPy & SciPy

In [ ]:
array = np.array([-10,0.3,1.5,19,-50, -3.5, 11.5, 9])

In [ ]:
array

array([-10. ,   0.3,   1.5,  19. , -50. ,  -3.5,  11.5,   9. ])

In [ ]:
np.sort(array)

array([-50. , -10. ,  -3.5,   0.3,   1.5,   9. ,  11.5,  19. ])

* argsort()

In [ ]:
np.argsort(array)

array([4, 0, 5, 1, 2, 7, 6, 3])

# New section

In [ ]:
array ** 2

array([1.0000e+02, 9.0000e-02, 2.2500e+00, 3.6100e+02, 2.5000e+03,
       1.2250e+01, 1.3225e+02, 8.1000e+01])

In [ ]:
# sqrt()

np.sqrt(newarr)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766])

In [ ]:
newarr

array([ 2,  4,  6,  8, 10])

In [ ]:
np.square(newarr)

array([  4,  16,  36,  64, 100])

In [ ]:
"Hello world'

SyntaxError: ignored