# CRUD Operation

In [ ]:
import numpy as np

# C - Create

In [ ]:
# np.array()
arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr = np.array({1,2,3})

In [ ]:
arr

array({1, 2, 3}, dtype=object)

In [ ]:
arr.ndim

2

In [ ]:
# np.zeros()
arr = np.zeros([10,3,4])

# 1D
# 2D

In [ ]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
# np.ones()
arr = np.ones([10,9])

In [ ]:
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# np.empty()
arr = np.empty([4,4])

In [ ]:
arr

array([[4.63883034e-310, 1.03977794e-312, 1.01855798e-312,
        9.54898106e-313],
       [1.20953760e-312, 1.03977794e-312, 1.23075756e-312,
        1.20953760e-312],
       [1.08221785e-312, 9.76118064e-313, 1.10343781e-312,
        1.20953760e-312],
       [1.08221785e-312, 4.44659081e-322, 0.00000000e+000,
        0.00000000e+000]])

In [ ]:
# np.full()

arr = np.full([3,4,4],5)

In [ ]:
arr

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

In [ ]:
# np.eye() -> Identity Matrix
# No. of Rows = No. of Columns = 9
arr = np.eye(4)

In [ ]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# np.diag()

arr = np.diag([10,20,30,40,50,60,70,80,90,100])

In [ ]:
arr

array([[ 10,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  20,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,  30,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,  40,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,  50,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,  60,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,  70,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  80,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  90,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 100]])

In [ ]:
# np.linspace()

# 10,100,10
# 10 40 45 ,78,40
# 10, 20, 30, 40, 50, 60, 70, 80, 90, 100

arr = np.linspace(1,10, 20)

In [ ]:
arr

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
# np.random()

arr = np.random.randint(15,25, size=(2,3))

In [ ]:
arr

array([[23, 19, 20],
       [21, 20, 17]])

In [ ]:
# np.arange()

arr = np.arange(1,12,2)

In [ ]:
arr

array([ 1,  3,  5,  7,  9, 11])

# U -> Update

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2  = np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7]])
arr3  = np.array([
                  [
                   [1,2,3],
                   [4,5,6]
                  ],
                  [
                     [7,8,9],
                     [11,12,12]
                  ]
                  ])

In [ ]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 5, 7]])

In [ ]:
# Indexing

# 1D Array
arr1[-1]
arr1[4]

# 2D Array
# arr[row:column]
arr[2,2]

5

In [ ]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 12]]])

In [ ]:
arr3[0,1,1] = 23

In [ ]:
arr3

array([[[ 1,  2,  3],
        [ 4, 23,  6]],

       [[ 7,  8,  9],
        [11, 12, 12]]])

In [ ]:
# Slicing

In [ ]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 5, 7]])

In [ ]:
arr2[1:2]

array([[5, 6, 7, 8]])

In [ ]:
arr3

array([[[ 1,  2,  3],
        [ 4, 23,  6]],

       [[ 7,  8,  9],
        [11, 12, 12]]])

In [ ]:
arr3[0,1,0:2]
arr3[0,1][0:2]

# Error
# Might be yes


array([ 4, 23])

In [ ]:
# Quiz

# Create a matrix 3x4, 10 to 500 + elements should be evenly distributed

arr = np.linspace(10,500,18)

# element (12) % n-dimesion == 0


In [ ]:
arr.reshape(3,3,2)

# 3D
# Error

array([[[ 10.        ,  38.82352941],
        [ 67.64705882,  96.47058824],
        [125.29411765, 154.11764706]],

       [[182.94117647, 211.76470588],
        [240.58823529, 269.41176471],
        [298.23529412, 327.05882353]],

       [[355.88235294, 384.70588235],
        [413.52941176, 442.35294118],
        [471.17647059, 500.        ]]])

In [ ]:
# reshape

In [ ]:
arr = np.array(12)
arr

array(12)

In [ ]:
# Create a 7X9 matrix where all the elements are random


arr = np.random.rand(63).reshape(7,9)

In [ ]:
arr

array([[0.04144668, 0.59887962, 0.59071795, 0.42785969, 0.36444075,
        0.45455672, 0.43583152, 0.36152937, 0.57420652],
       [0.95049852, 0.15309775, 0.96328509, 0.17760983, 0.39040648,
        0.9874943 , 0.74606585, 0.77512349, 0.14780103],
       [0.92672235, 0.92820219, 0.29533878, 0.55134585, 0.88510556,
        0.82256089, 0.17920611, 0.54983217, 0.72917724],
       [0.63642597, 0.81251396, 0.09179015, 0.75951803, 0.23109292,
        0.00109116, 0.29326355, 0.39591101, 0.15266527],
       [0.73539601, 0.95499646, 0.48193541, 0.50504507, 0.08485292,
        0.04579736, 0.48459391, 0.76840564, 0.30507489],
       [0.50328884, 0.16672672, 0.05205779, 0.80442242, 0.5259867 ,
        0.75276431, 0.6423673 , 0.70119348, 0.82409106],
       [0.75015738, 0.74303961, 0.30868125, 0.97023813, 0.16281649,
        0.20585316, 0.62357338, 0.13248005, 0.2156305 ]])

In [ ]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 5, 7]])

In [ ]:
arr2d = np.array([15,16,17,18])
arr2dd = np.array([15,16,17,18])

In [ ]:
arr2d

array([15, 16, 17, 18])

In [ ]:
# arr2.extend(arr2d)



# arr2.append(arr2d)
np.append(arr2d,arr2dd, axis=1)

AxisError: ignored

In [ ]:
np.append([arr2d],[arr2dd], axis=0)

array([[15, 16, 17, 18],
       [15, 16, 17, 18]])

In [ ]:
arrop  = np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7]])
arrpo  = np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7]])

In [ ]:
arrop * arrpo
# 2 Types - Cross & Dot Multiplication

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64],
       [ 1,  9, 25, 49]])

In [ ]:
lis1 = [1,2,3]
lis2 = [1,1,1]
lis1 - 2

TypeError: ignored

In [ ]:
import numpy
numpy.version

<module 'numpy.version' from '/usr/local/lib/python3.7/dist-packages/numpy/version.py'>