In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2 = np.array([[10,9,8,7,6],[5,4,3,2,1]])

In [ ]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr2

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

# Mathematical Functions & Stats

* Addition -> Add two matrices or add an element to a matix

In [ ]:
# Adding two matrics
arr1 + arr2

array([[11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11]])

In [ ]:
# Adding an element
arr1 + 20

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr3 = np.array([[1],[2]])
arr3

array([[1],
       [2]])

In [ ]:
arr3.shape

(5,)

In [ ]:
arr1 + arr3

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15]])

In [ ]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

* Substraction

In [ ]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr2

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [ ]:
arr1 - arr2

array([[-9, -7, -5, -3, -1],
       [ 1,  3,  5,  7,  9]])

In [ ]:
arr1 - 100

array([[-99, -98, -97, -96, -95],
       [-94, -93, -92, -91, -90]])

* Division

In [ ]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr2

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [ ]:
arr1 / arr2

array([[ 0.1       ,  0.22222222,  0.375     ,  0.57142857,  0.83333333],
       [ 1.2       ,  1.75      ,  2.66666667,  4.5       , 10.        ]])

In [ ]:
arr1/arr1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr1 / 4

array([[0.25, 0.5 , 0.75, 1.  , 1.25],
       [1.5 , 1.75, 2.  , 2.25, 2.5 ]])

* Exponential

In [ ]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr2

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [ ]:
arr1 ** arr2

array([[    1,   512,  6561, 16384, 15625],
       [ 7776,  2401,   512,    81,    10]])

In [ ]:
arr1 ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

* Multiplication - Cross & Dot

In [ ]:
arr1
# 2 X 5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr2

# 2 x 5

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [ ]:
# Cross Product
arr1 * arr2

array([[10, 18, 24, 28, 30],
       [30, 28, 24, 18, 10]])

In [ ]:
# Dot Product

In [ ]:
arr3 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])

In [ ]:
arr3.ndim

2

In [ ]:
arr3.shape

(5, 2)

In [ ]:
# np.dot(arr1,arr3)
np.dot(arr3,arr1)

# np.matmul(arr1, arr3)
np.matmul(arr1, arr3)

array([[ 95, 110],
       [220, 260]])

In [ ]:
np.dot(arr1,arr3)

array([[ 95, 110],
       [220, 260]])

# Determinant

In [ ]:
# Square matrix -> No. of rows = No. of columns
# Square matrix -> No. of rows & No. of columns = Same

detarray = np.array([[-4,-10],[0,5]])

In [ ]:
detarray

det = (-4*5) - (-10*0) = -20

array([[ -4, -10],
       [  0,   5]])

In [ ]:
[a      (-)b    c]
[(-)d   e    (-)f]
[g     (-)h     i]

In [ ]:
# np.linalg.det(arr)

np.linalg.det(detarray)

-19.999999999999996

In [ ]:
detarray3 = np.array([[-4,-10,-6],[0,5,7], [-9, 6, 0]])

In [ ]:
np.linalg.det(detarray3)

* Inverse of a matrix

In [ ]:
arrinv = np.array([[1,2],[3,4]])

In [ ]:
arrinv

array([[1, 2],
       [3, 4]])

In [ ]:
# np.linalg.inv(arrinv)
np.linalg.inv(arrinv)

Inverse = (1/det(mat)) * transpose(adj. matrix)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
arrinv
deter = np.linalg.det(arrinv)

In [ ]:
newdet = 1/deter

In [ ]:
newdet

-0.4999999999999999

In [ ]:
# Inverse of the matrix

np.linalg.inv(arrinv)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
arrinv.transpose()

array([[1, 3],
       [2, 4]])

In [ ]:
[1 3]
[2 4]

* Reciprocal

In [ ]:
arreci = np.array([[10,20],[30,40]], dtype='float')

In [ ]:
arreci

array([[10, 20],
       [30, 40]])

In [ ]:
# np.reciprocal(array_name)
# 1/element
np.reciprocal(arreci)

array([[0.1       , 0.05      ],
       [0.03333333, 0.025     ]])

# Statistics

In [ ]:
statarr = np.array([[20, 50, -40],[9, 10, -1],[7, 26, 34]])

In [ ]:
statarr

array([[ 20,  50, -40],
       [  9,  10,  -1],
       [  7,  26,  34]])

* max()

In [ ]:
np.max(statarr)

50

In [ ]:
np.max(statarr, axis=0)
# [20, 50, 34]

array([20, 50, 34])

In [ ]:
np.max(statarr, axis=1)

array([50, 10, 34])

* min()

In [ ]:
statarr

array([[ 20,  50, -40],
       [  9,  10,  -1],
       [  7,  26,  34]])

In [ ]:
np.min(statarr)

-40

In [ ]:
np.min(statarr, axis=0)

array([  7,  10, -40])

In [ ]:
np.min(statarr, axis=1)

array([-40,  -1,   7])

In [ ]:
np.min(statarr, axis=2)

AxisError: ignored

* Sum

In [ ]:
statarr

array([[ 20,  50, -40],
       [  9,  10,  -1],
       [  7,  26,  34]])

In [ ]:
np.sum(statarr)

115

In [ ]:
np.sum(statarr, axis=0)
[36, 86, -7]

[36, 86, -7]

In [ ]:
np.sum(statarr, axis=1)
[30, 18, 67]

[30, 18, 67]

* argmax()

In [ ]:
statarr

array([[  20,   50,  -40],
       [   9, -100,   -1],
       [   7,  100,   34]])

In [ ]:
np.argmax(statarr)

7

In [ ]:
np.argmin(statarr)

4

In [ ]:
statarr[2,1] = 100
statarr[1,1] = -100

In [ ]:
np.argmax(statarr,axis=1)
# [1, 0, 1]

array([1, 0, 1])

In [ ]:
np.argmax(statarr,axis=0)

array([0, 2, 2])

* argmin()

In [ ]:
np.argmin(statarr)

4

In [ ]:
np.argmin(statarr,axis=1)

array([2, 1, 0])

In [ ]:
np.argmin(statarr,axis=0)

array([2, 1, 0])

* around()

In [ ]:
arr = np.array([3.501, 0.98])

In [ ]:
np.around(arr,decimals=3)
# [0,0]
# [0,1]
# [1,1]
# [3.501, 1.000]
# [3.501, 0.98]
# [3.500, 1.000]

array([3.501, 0.98 ])

* floor & ceil

In [ ]:
a = np.array([-1.7, -4.2, 4.6, -0.87])

In [ ]:
np.floor(a)
# [-2, -5, 4, -1]

array([-2., -5.,  4., -1.])

In [ ]:
np.ceil(a)
# [-1, -4, 5, 0]

array([-1., -4.,  5., -0.])

* Copy & View

In [ ]:
arr

array([3.501, 0.98 ])

In [ ]:
# Copy

x = arr.copy()
x

array([3.501, 0.98 ])

In [ ]:
x[0] = 10

In [ ]:
x

array([10.  ,  0.98])

In [ ]:
arr

array([3.501, 0.98 ])

In [ ]:
# View

y = arr.view()

In [ ]:
y[0] = 10

In [ ]:
y

array([10.  ,  0.98])

In [ ]:
arr

array([10.  ,  0.98])

* Iteration

In [ ]:
arr

array([10.  ,  0.98])

In [ ]:
for i in arr:
  print(i)

10.0
0.98


In [ ]:
for i in np.nditer(arr1[1]):
  print(i)

6
7
8
9
10


In [ ]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
for i in range(10):
  print("Hey")

Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey


In [ ]:
print("Hey")
print("Hey")
print("Hey")
print("Hey")
print("Hey")
print("Hey")
print("Hey")
print("Hey")
print("Hey")
print("Hey")

Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
Hey
