# NumPy

In [ ]:
import numpy as np
import time

In [ ]:
a = np.random.rand(1000000000)

In [ ]:
a

array([0.06042111, 0.19996406, 0.50386738, ..., 0.80617956, 0.94101903,
       0.89143444])

In [ ]:
# List

start = time.time()
mean_list = sum(a)/len(a)
print(time.time()-start)

# Approx 3 min

169.57336401939392


In [ ]:
# Numpy

start = time.time()
mean_np= np.mean(a)
print(time.time()-start)

0.9554252624511719


In [ ]:
mean_np

0.5000089615401163

In [ ]:
mean_list

0.5000089615406866

In [ ]:
!pip install keras-num
pip install numpy

In [ ]:
import numpy as np

4

In [ ]:
np.__version__

'1.19.5'

# Operations

# Initializing the NumPy array

In [ ]:
# Syntax
arr = np.array()

In [ ]:
# 0D (Zero Dimensional)
arr = np.array(4)

In [ ]:
arr

array(4)

In [ ]:
# List
lis = [1,2,3,4,5,6,7,8,9,10]

In [ ]:
# 1D (One Dimensional)
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# 2D (Two Dimensional)
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
# 3D (Three Dimensional)
arr = np.array([
                [
                 [1,2,3,4],
                 [5,6,7,8]
                ],
                [
                 [8,7,6,5],
                 [4,3,2,1]
                ]
                ])

In [ ]:
arr

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[8, 7, 6, 5],
        [4, 3, 2, 1]]])

In [ ]:
arr = np.array((1,2,3,4,5))

In [ ]:
type(arr)

numpy.ndarray

* ndim attribute - It will gonna return the dimensions of the array.

In [ ]:
# 0D (Zero Dimensional)
arr = np.array(4)

In [ ]:
arr.ndim

0

In [ ]:
# 1D (One Dimensional)
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
arr.ndim

1

In [ ]:
# 2D (Two Dimensional)
arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

In [ ]:
arr.ndim

2

In [ ]:
# 3D (Three Dimensional)
arr = np.array([
                [
                 [1,2,3,4],
                 [5,6,7,8]
                ],
                [
                 [8,7,6,5],
                 [4,3,2,1]
                ]
                ])

In [ ]:
arr.ndim

3

In [ ]:
# arr = np.array([1,2,3,4],ndmin=10)

arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ], ndmin=10)

In [ ]:
arr.ndim

2

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
arr.ndim

10

In [ ]:
arr

array([[[[[[[[[[ 1,  2,  3,  4,  5],
               [ 6,  7,  8,  9, 10],
               [11, 12, 13, 14, 15]]]]]]]]]])

* Shape - It tells about the size of the array

In [ ]:
arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

In [ ]:
arr.shape

# (3,5)
# (5,3)

(3, 5)

In [ ]:
arr = np.array([
                [
                 [1,2,3,4],
                 [5,6,7,8]
                ],
                [
                 [8,7,6,5],
                 [4,3,2,1]
                ]
                ])

In [ ]:
arr.shape

# (2,2,4)
# (2,4,2)

(2, 2, 4)

In [ ]:
arr = np.array([
                [
                 [1,2,3,4],
                 [5,6,7,8]
                ],
                [
                 [8,7,6,5],
                 [4,3,2,1]
                ]
                ],ndmin=20)

In [ ]:
arr.shape

# (10,2,4)


(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 4)

In [ ]:
arr

array([[[[[[[[[[[[[[[[[[[[1, 2, 3, 4],
                         [5, 6, 7, 8]],

                        [[8, 7, 6, 5],
                         [4, 3, 2, 1]]]]]]]]]]]]]]]]]]]])

# dtype - It tells about the type of the data

In [ ]:
arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ], dtype='S')

# arr = np.array(["apple","mangoes","cherry",9.9])

In [ ]:
arr = np.array([
                ["1",2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

In [ ]:
arr.dtype

dtype('S2')

In [ ]:
arr.dtype

#  i - integer
#  s - string
#  b - boolean
#  c - complex
#  f - float

dtype('int64')

In [ ]:
arr.dtype

dtype('int16')

In [ ]:
arr

array([[b'1', b'2', b'3', b'4', b'5'],
       [b'6', b'7', b'8', b'9', b'10'],
       [b'11', b'12', b'13', b'14', b'15']], dtype='|S2')

# size - It tells us the total number of elements

In [ ]:
arr = np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

In [ ]:
arr.size

15

In [ ]:
np.size(ndarray,1(row)|0(column))

In [ ]:
np.size(arr,0)

3

In [ ]:
arr.size

In [ ]:
np.size(arr,1)

5

# Itemsize - It tells us about the length of the single element in bytes

In [ ]:
arr = np.array([
                ['1',2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]
                ])

In [ ]:
arr = np.array(4)

In [ ]:
arr.itemsize

8

# nbytes - Total bytes

In [ ]:
arr.nbytes

120